// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Purse.Backend.Data;

#nullable disable

namespace Purse.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401103039_AddMontantReserve")]
    partial class AddMontantReserve
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Purse.Backend.Models.BonCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("DemandeId")
                        .HasColumnType("int");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<string>("Po")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeId");

                    b.HasIndex("FournisseurId");

                    b.ToTable("BonCommandes");
                });

            modelBuilder.Entity("Purse.Backend.Models.Capex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BudgetRestant")
                        .HasColumnType("float");

                    b.Property<double>("BudgetTotal")
                        .HasColumnType("float");

                    b.Property<string>("Devis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCapex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Capexes");
                });

            modelBuilder.Entity("Purse.Backend.Models.Demande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapexId")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidationAchat1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidationAchat2")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MontantReserve")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RFX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapexId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Demandes");
                });

            modelBuilder.Entity("Purse.Backend.Models.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departements");
                });

            modelBuilder.Entity("Purse.Backend.Models.DetailsDemande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DemandeId")
                        .HasColumnType("int");

                    b.Property<string>("Devis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<double?>("Prix")
                        .HasColumnType("float");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DemandeId");

                    b.HasIndex("FournisseurId");

                    b.ToTable("DetailsDemandes");
                });

            modelBuilder.Entity("Purse.Backend.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("Purse.Backend.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DemandeId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Purse.Backend.Models.TauxChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DevisCible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevisSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Taux")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TauxChanges");
                });

            modelBuilder.Entity("Purse.Backend.Models.TransactionCapex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapexId")
                        .HasColumnType("int");

                    b.Property<int>("DemandeId")
                        .HasColumnType("int");

                    b.Property<int>("Po")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapexId");

                    b.HasIndex("DemandeId");

                    b.ToTable("TransactionCapex");
                });

            modelBuilder.Entity("Purse.Backend.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("ChefId")
                        .HasColumnType("int");

                    b.Property<int>("DepartementId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChefId");

                    b.HasIndex("DepartementId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Purse.Backend.Models.BonCommande", b =>
                {
                    b.HasOne("Purse.Backend.Models.Demande", "Demande")
                        .WithMany("BonsCommande")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Purse.Backend.Models.Fournisseur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId");

                    b.Navigation("Demande");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("Purse.Backend.Models.Demande", b =>
                {
                    b.HasOne("Purse.Backend.Models.Capex", "Capex")
                        .WithMany("Demandes")
                        .HasForeignKey("CapexId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Purse.Backend.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capex");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Purse.Backend.Models.DetailsDemande", b =>
                {
                    b.HasOne("Purse.Backend.Models.Demande", "Demande")
                        .WithMany("Details")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Purse.Backend.Models.Fournisseur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Demande");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("Purse.Backend.Models.Notification", b =>
                {
                    b.HasOne("Purse.Backend.Models.Demande", "Demande")
                        .WithMany("Notifications")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("Purse.Backend.Models.TransactionCapex", b =>
                {
                    b.HasOne("Purse.Backend.Models.Capex", "Capex")
                        .WithMany("Transactions")
                        .HasForeignKey("CapexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Purse.Backend.Models.Demande", "Demande")
                        .WithMany("Transactions")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Capex");

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("Purse.Backend.Models.Utilisateur", b =>
                {
                    b.HasOne("Purse.Backend.Models.Utilisateur", "Chef")
                        .WithMany()
                        .HasForeignKey("ChefId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Purse.Backend.Models.Departement", "Departement")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chef");

                    b.Navigation("Departement");
                });

            modelBuilder.Entity("Purse.Backend.Models.Capex", b =>
                {
                    b.Navigation("Demandes");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Purse.Backend.Models.Demande", b =>
                {
                    b.Navigation("BonsCommande");

                    b.Navigation("Details");

                    b.Navigation("Notifications");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Purse.Backend.Models.Departement", b =>
                {
                    b.Navigation("Utilisateurs");
                });
#pragma warning restore 612, 618
        }
    }
}
